### PR TITLE
fix: clarify `Group.addMember` error message

### LINKED ISSUE #2375: Bug: improve error messages for addMember failures
Now it simply says "Failed to set role""

It should explain the reason why it failed.

### PR DESCRIPTION
**Pull request by emmyoh**
Closes #2375.

### CODE REVIEW

File: packages/cojson/src/coValues/group.ts [hunk 1]
```diff
@@ -292,7 +292,7 @@ export class RawGroup<
       this.set(account, role, "trusting");
 
       if (this.get(account) !== role) {
-        throw new Error("Failed to set role");
+        throw new Error("Failed to set role due to insufficient permissions");
```
Comment (gdorsi) [inline packages/cojson/src/coValues/group.ts]: **suggestion:** how about specifying the current role of the account?

It would help in getting a better understanding of the error

Comment (emmyoh) [reply packages/cojson/src/coValues/group.ts]: Great idea. On it

Comment (emmyoh) [reply packages/cojson/src/coValues/group.ts]: > **suggestion:** how about specifying the current role of the account?
> 
> It would help in getting a better understanding of the error

Like [this](https://github.com/garden-co/jazz/pull/2439/commits/780961d46fad570ee57a2465eed424cfc9eb6d10), yeah?

File: packages/cojson/src/tests/permissions.test.ts [hunk 2]
```diff
@@ -81,7 +81,7 @@ test("Admins can't demote other admins in a group (high level)", () => {
   );
 
   expect(() => groupAsOtherAdmin.addMemberInternal(admin.id, "writer")).toThrow(
-    "Failed to set role",
+    "Failed to set role due to insufficient permissions (role of current account is admin)",
```
Comment (gdorsi) [inline packages/cojson/src/tests/permissions.test.ts]: This error message is misleading.

I think we should have a specific message for this case, especially because without reading the docs is hard to understand why an admin has insufficient permissions.

Comment (emmyoh) [reply packages/cojson/src/tests/permissions.test.ts]: Good idea. Will do this this morning

File: packages/cojson/src/coValues/group.ts [hunk 3]
```diff
@@ -292,7 +292,12 @@ export class RawGroup<
       this.set(account, role, "trusting");
 
       if (this.get(account) !== role) {
-        throw new Error("Failed to set role");
+        const myRole = this.myRole();
+        throw new Error(
+          myRole === "admin"
+            ? "Administrators cannot demote other administrators in a group"
```
Comment (gdorsi) [inline packages/cojson/src/coValues/group.ts]: This is valid only when both roles are admin.

If I'm admin, and the other member is not an admin (which I don't recall a case for this to happen) we should at least trigger a more generic error.

There might be a bug in the permissions and we don't want to give the wrong error message.

Comment (emmyoh) [reply packages/cojson/src/coValues/group.ts]: Should now be fixed. Thanks

**Review by gdorsi — APPROVED** [review]
LGTM, thanks!
